- name: Install Python dependencies for Docker modules
  block:
    - name: Install pip and python-requests (RHEL/Alma)
      dnf:
        name:
          - python3-pip
          - python3-requests
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install python-requests (Debian/Ubuntu)
      apt:
        name: python3-requests
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"