---
additional_credentials:
  - usernamePassword:
      scope: SYSTEM
      id: "docker-registry-credentials"
      username: "docker-user"
      password: "docker-password"
      description: "Docker Registry Credentials"
  - usernamePassword:
      scope: GLOBAL
      id: "github-access"
      username: "my-github-user"
      password: "ghp-secret-token"
      description: "GitHub Access Token"
